import snakeUnitTests from './snakeUnitTests.js'
import boardUnitTests from './boardUnitTests.js'
import pillUnitTests from './pillUnitTests.js'
import intCoordinateUnitTests from './intCoordinateUnitTests.js';
import canvasWrapperUnitTests from './canvasWrapperUnitTests.js';
import notifierUnitTests from './notifierUnitTests.js';
import commandUnitTests from './commandUnitTests.js';
import mainUnitTests from './mainUnitTests.js';
import aStarAlgorithmUnitTests from './aStarAlgorithmUnitTests.js';